version: '3.9'
services:
  app:
    image: practice9_efcore_catalog:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12442
      POSTGRES_DB: EFCorePractice
    ports:
      - "5432:5432"
