// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Practice9_EFCore.Domain;

#nullable disable

namespace Practice9_EFCore.Infrastructure.Migrations
{
    [DbContext(typeof(CompaniesDbContext))]
    [Migration("20240821110622_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CompanyEntityRubricEntity", b =>
                {
                    b.Property<Guid>("CompaniesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RubricsId")
                        .HasColumnType("uuid");

                    b.HasKey("CompaniesId", "RubricsId");

                    b.HasIndex("RubricsId");

                    b.ToTable("CompanyEntityRubricEntity");
                });

            modelBuilder.Entity("Practice9_EFCore.Domain.Models.BuildingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("XPosition")
                        .HasColumnType("double precision");

                    b.Property<double>("YPosition")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Buildings");
                });

            modelBuilder.Entity("Practice9_EFCore.Domain.Models.CompanyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<string>>("Phones")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Practice9_EFCore.Domain.Models.RubricEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentRubricId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParentRubricId");

                    b.ToTable("Rubrics");
                });

            modelBuilder.Entity("CompanyEntityRubricEntity", b =>
                {
                    b.HasOne("Practice9_EFCore.Domain.Models.CompanyEntity", null)
                        .WithMany()
                        .HasForeignKey("CompaniesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Practice9_EFCore.Domain.Models.RubricEntity", null)
                        .WithMany()
                        .HasForeignKey("RubricsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Practice9_EFCore.Domain.Models.CompanyEntity", b =>
                {
                    b.HasOne("Practice9_EFCore.Domain.Models.BuildingEntity", "Building")
                        .WithMany("Companies")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("Practice9_EFCore.Domain.Models.RubricEntity", b =>
                {
                    b.HasOne("Practice9_EFCore.Domain.Models.RubricEntity", "ParentRubric")
                        .WithMany("InnerRubrics")
                        .HasForeignKey("ParentRubricId");

                    b.Navigation("ParentRubric");
                });

            modelBuilder.Entity("Practice9_EFCore.Domain.Models.BuildingEntity", b =>
                {
                    b.Navigation("Companies");
                });

            modelBuilder.Entity("Practice9_EFCore.Domain.Models.RubricEntity", b =>
                {
                    b.Navigation("InnerRubrics");
                });
#pragma warning restore 612, 618
        }
    }
}
